# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protoc.object_detection import object_detection_pb2 as protoc_dot_object__detection_dot_object__detection__pb2


class ObjectDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DetectImage = channel.unary_unary(
                '/ObjectDetection.ObjectDetection/DetectImage',
                request_serializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionRequest.SerializeToString,
                response_deserializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionResponse.FromString,
                )
        self.DetectStream = channel.stream_stream(
                '/ObjectDetection.ObjectDetection/DetectStream',
                request_serializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionRequest.SerializeToString,
                response_deserializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionResponse.FromString,
                )


class ObjectDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DetectImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DetectImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectImage,
                    request_deserializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionRequest.FromString,
                    response_serializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionResponse.SerializeToString,
            ),
            'DetectStream': grpc.stream_stream_rpc_method_handler(
                    servicer.DetectStream,
                    request_deserializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionRequest.FromString,
                    response_serializer=protoc_dot_object__detection_dot_object__detection__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ObjectDetection.ObjectDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ObjectDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DetectImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ObjectDetection.ObjectDetection/DetectImage',
            protoc_dot_object__detection_dot_object__detection__pb2.DetectionRequest.SerializeToString,
            protoc_dot_object__detection_dot_object__detection__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DetectStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ObjectDetection.ObjectDetection/DetectStream',
            protoc_dot_object__detection_dot_object__detection__pb2.DetectionRequest.SerializeToString,
            protoc_dot_object__detection_dot_object__detection__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
